version: '3.8'
services:
  database:
    container_name: database
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: bernhaeckt
    ports:
      - "5432:5432"
    expose:
      - "5432"
