version: '3.8'
services:
  database:
    container_name: database
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: bernhaeckt
    ports:
      - "5432:5432"
    expose:
      - "5432"
  ui:
    container_name: ui
    build:
      context: ../ui/sustainability-ui
      target: builder
    ports:
      - 80:80
    volumes:
      - ../ui/sustainability-ui:/project
      - /project/node_modules
  
